# Samples, populations estimates and their uncertainty

Scientific studies only occasionally gathers all available data regarding some phenomena under study. All possible data are not available to us due to e.g. practical or economical reasons. We therefore have no direct way of studying all elderly peoples responses to training or the relationship between strength and performance in all cyclists etc. The scientist therefore faces the challenge of drawing conclusion about all possible observations, based on a limited set of observations that we actually have access to.

All possible observations are often referred to as the *population* while the data that we have access to is called the *sample*. When we make claims about the *population* using the sample we draw *inference*. Our ability to accurately draw inference (or conclusions) about the population based on our sample is determined by the way we have gathered data. A sample is *unbiased* when it represents the population under study. By *random sampling* from the population we can be pretty sure that we in most cases have an representative sample, free from bias. Bias may be a consequence of systematic aspects of our sampling scheme, e.g., when studying healthy individuals responses to exercise, recruitment to the study may introduce bias as we are more likely to recruit participants that actually want to do exercise.        
