project:
  type: book
  output-dir: docs

book:
  title: "Quantitative methods and statistics (In Sport and Exercise Science)"
  author: "Daniel Hammarström"
  date: "2023-07-31"
  search: true
  repo-url: https://github.com/dhammarstrom/quant-methods
  repo-branch: master
  repo-actions: [edit, issue, source]
  downloads: [epub]
  chapters:
    - index.qmd
    - 01-intro-to-data.qmd
    - 02-spreadsheets.qmd
    - 03-intro-to-r.qmd
    - 04-first-graph.qmd
    - 05-first-tables.qmd
    - 06-writing-reports.qmd
    - 07-version-control-git.qmd
    - 08-phys-lab-reliability.qmd
    - 10-mol-lab-intro.qmd

bibliography: resources/bib-final.bib
format:
  html:
    theme:
      light: flatly
      dark: darkly
  epub:
    cover-image: resources/cover.png