project:
  type: book
  output-dir: docs

book:
  title: "Quantitative methods and statistics (In Sport and Exercise Science)"
  author: "Daniel Hammarström"
  date: "2023-07-31"
  chapters:
    - index.qmd
    - 01-intro-to-data.qmd
    - 02-spreadsheets.qmd
    - 03-intro-to-r.qmd
    - 04-first-graph.qmd

bibliography: resources/bib-final.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  epub:
    cover-image: resources/cover.png