
```{r nojekyll}
#| warning: false
#| message: false
#| echo: false
#| include: false




```


# Introduction {.unnumbered}













## Prerequisites

To fully benefit from the course I recommend that students bring a basic understanding of statistical concepts to the course, such as knowledge about descriptive data summarises, usage of inferential statistics and regression models. We aim to cover these concepts in the course but also hope to get further. If you are not sure your basic understanding is up to date you may want to review introductory material, such as [Statistisk dataanalyse med jamovi](https://dhammarstrom.github.io/statistisk-dataanalyse/).

In the course we will use R to do analyses, create figures and tables, and write reports. If you are unfamiliar with R, that is OK, the course hopefully provides a gentle introduction. Using R, together with additional data science tools, means that you will encounter many infuriating problems. Such problems might arise from a missing comma or a misspelled word making your computer program produce [gibberish](https://en.wikipedia.org/wiki/Gibberish). Solving such problems requires patience, systematic thinking and a positive attitude! The skill set I hope you will develop during the course includes knowledge about how to identify problems, where to find help to address problems and how to learn from problems.

If you feel that R is not for you, that's ok, the course will also provide examples of how to do analyses in two other open source software packages, [jamovi](https://www.jamovi.org/) and [JASP](https://jasp-stats.org/). These software packages are user friendly and have a graphical user interface. They are also based on R, so you can use them to learn R if you want to. 




