---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Study questions {#study-questions}

*Updates:* Chapters 2-6 updated on 2021-08-31

## Chapter 2: Introduction to data science (with relevant literature)

- Define the PPDAC cycle. What are the components of this cycle?
- What is the difference between a reprodicible study and a replicated study?
- What defines reproducible science?
- What do we mean by scripted code vs. "point-and-click".


## Chapter 3: Storing data in spreadsheets (with relevant literature)

- Make a short list of suggestions on how to use spreadsheet software based on the reccomendations from Broamn and Woo.
- Define the following concepts in a spreadsheet: Cell, formula, function, attributes.
- Define the Anna Kerenina principle. How does it apply to data science and data sets?
- Define tidy data.
- How would you structure a spreadsheet in order to adhere to tidy data principles?
- What does it mean to be lazy when recording data?
- What is data validation, and how do you turn it on in your spreadsheet software?
- What are the differences between `.csv` and `.xls(x)` files?

## Chapter 4: Installing and starting up R (and R Studio)

- Make sure you have working installations of R and RStudio.
- How would you define, the source, the environment, the console.
- When typing the code shown below in your console, what happends to the environment, what does this mean?

```{r, eval = FALSE}
obj <- c(1, 2, 3, 56)
```

- How would you define `obj` in the code above?
- What is the `c(1, 2, 3, 56)` part doing in the code?
- What is `<-`?
- What is a R package?
- What is the difference between reproducible and non-reproducible computing?
- What is a script?
- How does a simple computer program work?
- Why should you never save the workspace?


## Chapter 5: Creating your first graph

- Define the following: aesthetics, geoms, mapping, theme.
- Think about situations when it would be appropriate to use the following: `geom_point()`, `geom_boxplot()`, `geom_line()`, `geom_jitter()`.


## Chapter 6: Wrangling data to create your first table

- What do we mean with data wrangling?
- What is a pipe?
- Define (in plain language) the `%>%` operator.
- When using `%>%`, what makes a function pipable?
- Why do you put `print()` in the end of every pipe (when developing it)?
- Functions in the package `dplyr` can be useful when wrangling data, define the folowing functions, when do you use them?
  - `filter()`
  - `select()` 
  - `mutate()`
- Define grouped operations using `group_by()`.
- What will be the difference of using `group_by()` followed by `summarise()` as opposed to `mutate()`.
- Define the functions `pivot_wider()` and `pivot_longer()`.
- What is needed to make a table using `kable()` try to define (with plain language) how you need to set up your software.


## Chapter 11: Introduction to the molecular exercise physiology lab

- Discuss: What are the most important points concerning health and safety in the laboratory? Your answer could involve before, during and after the experiment.
- Why do we use a laboratory notebook?


- Convert 1 gram to milligrams
- Convert 1 milligram to micrograms
- Convert 1 litre to millilitres
- Convert 500 millilitres to litres
- Convert 10 microlitres to millilitres

- You are to make a 1 Molar Tris solution (Tris MW = 121.14 g/mol). How much Tris should you add to your solution?
- In the same solution, we want to add 0.5 M of NaCl (NaCl MW = 58 g/mol), how much NaCl should go int your solution?

- To create a reagent (Reagent B), we will add EDTA from a *Stock solution* with a concentration of 0.5 M. The final concentration should be 0.06 M in 1 litre. What volume stock solution should be added to your reagent? Use the formula below to answer the question:

$$C_1 \times V_1 = C_2 \times V_2$$
One unknown can be calculated from the formula by rearranging:

$$V_2 = \frac{C_1 \times V_1}{C_2}$$

$V$ for volume and $C$ for concentration.








